// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3nqGh-9atrR8Ju0Sr7tz6p85a6Xfjuw',
    appId: '1:608278786808:web:7271a8b9a5b54f9305010d',
    messagingSenderId: '608278786808',
    projectId: 'proyectointegrador2-4198d',
    authDomain: 'proyectointegrador2-4198d.firebaseapp.com',
    databaseURL: 'https://proyectointegrador2-4198d-default-rtdb.firebaseio.com',
    storageBucket: 'proyectointegrador2-4198d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi78ZAbipvzU-95ClhXGPltKk3nRQmo60',
    appId: '1:608278786808:android:d93a24bbf71d3eed05010d',
    messagingSenderId: '608278786808',
    projectId: 'proyectointegrador2-4198d',
    databaseURL: 'https://proyectointegrador2-4198d-default-rtdb.firebaseio.com',
    storageBucket: 'proyectointegrador2-4198d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoyMBsBeLktTmjFIjDsvb5imurDBV7c0',
    appId: '1:608278786808:ios:cf7e192b406a40aa05010d',
    messagingSenderId: '608278786808',
    projectId: 'proyectointegrador2-4198d',
    databaseURL: 'https://proyectointegrador2-4198d-default-rtdb.firebaseio.com',
    storageBucket: 'proyectointegrador2-4198d.appspot.com',
    iosClientId: '608278786808-4i9t4prlei4r6hpdap3b333u635ko6vb.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.pruebafirebase',
  );
}
